# Generated by Django 6.0 on 2025-12-16 12:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indgedient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naziv sastojka', max_length=150)),
                ('code', models.CharField(help_text='Sifra sastojka', max_length=15)),
                ('description', models.TextField(help_text='Opis sastojka', max_length=150)),
                ('base_price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.00'), help_text='Osnovna cijena', max_digits=18)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
    ]
