# Generated by Django 6.0 on 2025-12-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indgedient',
            new_name='Ingredient',
        ),
    ]
