# Generated by Django 6.0 on 2025-12-19 11:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_indgedient_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price_modificator',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('1.00'), help_text='Modifikator cijene', max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), help_text='Ukupna cijena sastojka', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.00'), help_text='Osnovna cijena sastojka', max_digits=18),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='code',
            field=models.CharField(help_text='Šifra sastojka', max_length=15),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(help_text='Opis sastojka', max_length=750),
        ),
    ]
